### ISSUE TITLE
[Bug] Cutting Board Cannot Accept Hopper Inputs

### ISSUE THREAD

**Issue by Noobulus** [newhoryzon/farmers-delight-fabric#120] opened 2022-12-19 08:16 UTC
Cutting boards on the Forge version of Farmer's Delight will accept items via hoppers feeding into them, but cutting boards in this version do not.

**Comment by CZdigger146** [comment] 2023-01-06 19:56
I also have this problem, thaught it was caused by us migrating our modpack from forge to fabric and it's just a temporary "break and place back" bug, but it seems that no cutting board can accept items from hoppers:

![2023-01-06_20 41 22](https://user-images.githubusercontent.com/100414011/211088927-7652dc1c-0695-4934-aa3e-f7d36e569753.png)
![2023-01-06_20 41 26](https://user-images.githubusercontent.com/100414011/211088959-76e8f424-9776-4b15-8622-ddd95a262a51.png)

Our world depends on this functionality since we have several factories that use this and afaik there is no working way of automating the cutting board at the moment so we're kinda stuck until this is fixed... I can provide more info it it helps in any way though!

**Comment by Avakining** [comment] 2023-01-21 00:47
In addition to not accepting hopper inputs, it also seems to not accept pipes, Create deployers, or ME Pattern Providers as inputs. I can't find a single way to automate it right now

**Comment by VaelophisNyx** [comment] 2023-03-14 01:53
several months later, this still persists
please fix this, the cutting board is absurdly annoying to use as a result of this

**Comment by Avakining** [comment] 2023-03-14 05:07
> afaik there is no working way of automating the cutting board at the moment

Create deployers *do* work, but they take up much more space than hoppers.

**Comment by VaelophisNyx** [comment] 2023-03-14 14:42
issue is my server isn't using create

**Comment by Zifiv** [comment] 2023-05-11 03:03
Hello @VaelophisNyx,

Sorry for the late update on this error, it will be fixed by the issue #104 (I mark your issue as duplicate it is already fixed and ready for the next release).

**Closed by Zifiv** 2023-05-11 03:03 UTC
