### ISSUE TITLE
Mushroom Colony can't complete use scissors to cut out

### ISSUE THREAD

**Issue by cyuntp** [newhoryzon/farmers-delight-fabric#23] opened 2022-06-27 06:24 UTC
Minecraft 1.18.2 fabric Mushroom Colony can't complete use scissors to cut out
![image](https://user-images.githubusercontent.com/108256056/175873079-6ef3c28e-c9f5-4616-a89a-7cbf3cecf323.png)
![image](https://user-images.githubusercontent.com/108256056/175873108-47f98aa2-702b-4b09-9964-ccdaeb95ded5.png)

**Comment by Zifiv** [comment] 2022-06-27 19:23
Thanks to submit your issue :) ! I'll try reproduct it and came back here to give my feedback.

**Comment by cyuntp** [comment] 2022-06-28 11:10
I really like this mod！ hope you can stick to it 👍

**Comment by Zifiv** [comment] 2022-06-29 18:14
I'm actually concentrating all my free times to the 1.19 version of the mod to synchronized it with all features present in the last "Farmer's Delight" forge version (original version), so you bug issue will be added in the next milestone planed for the 1.18 upgrade version.

**Comment by Zifiv** [comment] 2022-07-05 17:30
It seems that the issue is fixed by the change of common tag used by the mod `c:` instead of `fabric:` (issue #18).

So I close this one. It will be fixed in the next release.

**Closed by Zifiv** 2022-07-05 17:30 UTC
Labels: bug
