### ISSUE TITLE
1.18.2fabric1.2.1 Why does the synthesis table of REI have an error with wike 

### ISSUE THREAD

**Issue by HG-Ted** [newhoryzon/farmers-delight-fabric#78] opened 2022-10-30 06:57 UTC
![image](https://user-images.githubusercontent.com/105895618/198866400-2b0f42b6-0a19-4562-8023-71fea7985e0d.png)
The latest version of REI's composition table is incorrect
Why does the synthesis table of REI have an error with wike

**Comment by JieningYu** [comment] 2022-10-30 09:25
The issue is that, all the recipes of dyed canvas signs are using `forge` tags namespace for dyes. Here we need to use `c` namespace and use [Forge Tags](https://github.com/AlphaMode/ForgeTags) for porting convenience. (if possible)

**Comment by Zifiv** [comment] 2022-10-30 10:03
Duplicate of #77.

**Closed by Zifiv** 2022-10-30 10:03 UTC
Labels: duplicate
