### ISSUE TITLE
Safe mode error.

### ISSUE THREAD

**Issue by g3b0800** [newhoryzon/farmers-delight-fabric#134] opened 2023-02-26 18:37 UTC
It brings up the safe mode error whenever I try to create a new world or play an already-created one. If I click it, it freezes for a second or two and nothing happens.  I've attached my mod list, without FD and any of its add-ons. Any sort of help would be appreciated.
![2](https://user-images.githubusercontent.com/126415477/221429785-f1d6b659-91d8-4d55-b958-01cecd815443.png)
![1](https://user-images.githubusercontent.com/126415477/221429786-61a9a4a7-ece9-4bed-a8d3-0e7abd5cee51.png)

![4](https://user-images.githubusercontent.com/126415477/221429782-e90dbac4-147a-46ec-8a44-2565a6fc0764.png)
![3](https://user-images.githubusercontent.com/126415477/221429784-cd22f2a5-6463-4461-996a-90157bb6341f.png)

**Comment by Zifiv** [comment] 2023-05-11 02:31
Hello @g3b0800,

Can you please add a pastbin with the log error that you have.
By the way, try to add only Farmer's Delight without any "addons" of it.

**Comment by xlifi** [comment] 2023-06-14 21:16
@g3b0800 to fix this you can install mods like "disable custom world advice"

**Comment by Linguardium** [comment] 2023-07-19 18:33
for anyone seeing this in the future: the safe mode error occurs when data pack loading fails. "disable custom world advice" does not fix data pack loading errors

**Comment by Zifiv** [comment] 2023-07-20 00:44
It seems that this is not an error caused by Farmer's Delight (I can't reproduce), the issue hasn't receive an update from the autor @g3b0800, so I close it.

Feel free to re-open it if you have any logs to help resolve this issue.

**Closed by Zifiv** 2023-07-20 00:44 UTC
Labels: invalid
