### ISSUE TITLE
Game exits and says "Server closed" when killing animals that has secondary drop with a knife

### ISSUE THREAD

**Issue by asodugf12** [newhoryzon/farmers-delight-fabric#27] opened 2022-07-07 15:43 UTC
I'll post the crash log here I just found it
Flint knives don't work with sheep however iron knives do
Both didn't work with pigs

[crash-2022-07-07_11.50.42-server.txt](https://github.com/newhoryzon/farmers-delight-fabric/files/9065399/crash-2022-07-07_11.50.42-server.txt)

**Comment by asodugf12** [comment] 2022-07-08 16:02
im not sure 
it only crashes when secondary drops appear so I assumed that was the case

**Comment by Zifiv** [comment] 2022-07-12 03:45
I can't reproduce your bug in the 1.19 and 1.18 versions of Farmer's Delight (tested in solo and multiplayer server).
Can you try update all versions of Fabric Loader, Fabric API and other mods to see if the bug still appear.

**Comment by asodugf12** [comment] 2022-07-14 18:23
i think you could try getting all the mods i was using
it is mentioned in the logs

**Comment by Zifiv** [comment] 2022-07-14 23:15
Do you have tried to reproduce it with your mod pack without Farmer's Delight, to be sure it appear only while Farmer's Delight is installed.

By the way, I've checked the issue tracker of the mod aimed by the crash log, "Clumps" and it seems that there were an issue (https://github.com/jaredlll08/Clumps/issues/62) that have been fix on the last version.

So I close this issue, I think you should listen to me, and update all your mods and Fabric API version, it will work well after 😉.

**Closed by Zifiv** 2022-07-14 23:15 UTC
Labels: bug, invalid, question, 1.18

**Comment by asodugf12** [comment] 2022-07-18 04:00
i removed clumps and it seemse to work
thank you very much for taking your time to help me!
