### ISSUE TITLE
[1.19.2]: Cannot plant seeds on Terrestria Farmland

### ISSUE THREAD

**Issue by Martmists-GH** [newhoryzon/farmers-delight-fabric#137] opened 2023-03-21 21:31 UTC
To reproduce:

1. Place Terrestria's Andisol Farmland
2. Attempt to plant the seed
3. The seed does not get planted

Other mods like Croptopia work fine, and regular farmland also works fine.

Versions:
Terrestria: 5.0.8
Farmer's Delight: 1.3.9
Fabric API: 0.76.0

---

Update: Cabbage seeds seem to work fine, maybe only tomato seeds are affected?

**Comment by Zifiv** [comment] 2023-07-08 12:40
Hello @Martmists-GH,

Thanks you for report the issue, this is already done and it's a duplicate of (#30, #90 and #157). It will be fixed in next release normaly.

**Closed by Zifiv** 2023-07-08 12:40 UTC
Labels: bug, duplicate

**Comment by Martmists-GH** [comment] 2023-07-08 12:56
From what I can gather in the related issues it's caused by MoreTags, however I do not have the mod installed, nor does any mod include it as dependency.
