### ISSUE TITLE
[Suggestion] EMI Compatability

### ISSUE THREAD

**Issue by Afrocntrik** [newhoryzon/farmers-delight-fabric#67] opened 2022-09-04 09:54 UTC
The Cooking Pot, Cutting Board and Decomposition currently don't show up as categories in [EMI](https://modrinth.com/mod/emi) as it currently does in REI.

**Comment by JieningYu** [comment] 2022-09-04 09:55
dupe of https://github.com/newhoryzon/farmers-delight-fabric/issues/19

**Closed** 2022-09-04 09:56 UTC
